import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from py.provider_registry import PROVIDER_MANIFEST

EXTENSION_IDS = {
    "zai": "zai", "deepseek": "deepseek", "arcee": "arcee", "gemini-web": "gemini",
    "lmarena": "lmarena", "google-ai-studio": "aistudio", "google-ai-studio-web": "aistudio-web",
    "inflection": "inflection", "grok": "grok", "kimi": "kimi", "inception": "inception",
    "longcat": "longcat", "mistral": "mistral", "mimo": "mimo", "openai-web": "chatgpt",
    "perplexity": "perplexity", "phind": "phind", "qwen-ai": "qwen", "glm-web": "chatglm",
}


def payloads():
    catalog = []
    schema = []
    for item in PROVIDER_MANIFEST:
        entry = {
            "id": item["id"], "owned_by": item["owned_by"], "models": list(item["models"]),
            "runtimes": list(item["runtimes"]), "auth_mode": item["auth_mode"],
            "credential_sets": [list(group) for group in item.get("credential_sets", ())],
        }
        catalog.append(entry)
        if item["id"] in EXTENSION_IDS:
            schema.append({**entry, "extension_id": EXTENSION_IDS[item["id"]]})
    catalog.sort(key=lambda x: x["id"])
    schema.sort(key=lambda x: x["extension_id"])
    catalog_json = json.dumps({"generated": True, "providers": catalog}, ensure_ascii=False, indent=2) + "\n"
    schema_js = "/* generated by scripts/generate_provider_artifacts.py */\nwindow.PROVIDER_SCHEMA = " + json.dumps(schema, ensure_ascii=False, indent=2) + ";\n"
    lines = ["# Generated provider catalog", "", "This file is generated from `py/provider_registry.py`. Do not edit it manually.", "", "| Provider | Models | Runtime | Auth | Credentials |", "| --- | ---: | --- | --- | --- |"]
    for item in catalog:
        credentials = " or ".join(" + ".join(group) for group in item["credential_sets"]) or "none"
        lines.append(f"| `{item['id']}` | {len(item['models'])} | {', '.join(item['runtimes'])} | {item['auth_mode']} | {credentials} |")
    return {
        ROOT / "generated" / "provider-catalog.json": catalog_json,
        ROOT / "extensions" / "credentials-exporter" / "provider-schema.js": schema_js,
        ROOT / "docs" / "provider-catalog.md": "\n".join(lines) + "\n",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mismatches = []
    for path, content in payloads().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if mismatches:
        print("stale generated provider artifacts: " + ", ".join(mismatches))
        return 1
    print("provider artifacts: " + ("fresh" if args.check else "generated"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
